trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- script: |
    echo "Current directory:"
    pwd

    echo ""

    echo "Repository contents:"
    ls -la

    echo ""

    echo "Docker version:"
    docker --version
  displayName: "Inspect Build Agent"

- script: |
    echo "Build ID: $(Build.BuildId)"
    echo "Repository: $(Build.Repository.Name)"
    echo "Branch: $(Build.SourceBranchName)"
    echo "Agent OS: $(Agent.OS)"
    echo "Working Directory: $(Build.SourcesDirectory)"
  displayName: "Display Built-in Variables"  

- task: PublishPipelineArtifact@1
  displayName: Publish Application

  inputs:
    targetPath: '$(Build.SourcesDirectory)/app'
    artifact: 'webapp'