trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  acrName: 'acrdevops001'
  acrLoginServer: 'acrdevops001.azurecr.io'
  imageName: 'my-devops-site'
  imageTag: '$(Build.BuildId)'

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Build and Push Docker Image to ACR'
  inputs:
    azureSubscription: 'sc-devops-dev'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name $(acrName)

      docker build -t $(acrLoginServer)/$(imageName):$(imageTag) ./app

      docker push $(acrLoginServer)/$(imageName):$(imageTag)

      docker tag $(acrLoginServer)/$(imageName):$(imageTag) $(acrLoginServer)/$(imageName):latest

      docker push $(acrLoginServer)/$(imageName):latest

